export const INCREMENT_COUNTER = "INCREMENT_COUNTER";
export const INCREMENT_MANY_COUNTER = "INCREMENT_MANY_COUNTER";
export const DECREMENT_COUNTER = "DECREMENT_COUNTER";
export const DECREMENT_MANY_COUNTER = "DECREMENT_MANY_COUNTER";
export const RESET_COUNTER = "RESET_COUNTER";
export const UNDO_COUNTER = "UNDO_COUNTER";
export const REDO_COUNTER = "REDO_COUNTER";
export const REMOVE_HISTORY = "REMOVE_HISTORY";