export const INCREMENT_COUNTER = "INCREMENT_COUNTER";
export const INCREMENT_MANY_COUNTER = "INCREMENT_MANY_COUNTER";
export const DECREMENT_COUNTER = "DECREMENT_COUNTER";
export const DECREMENT_MANY_COUNTER = "DECREMENT_MANY_COUNTER";
export const RESET_COUNTER = "RESET_COUNTER";